---
# There's a lot of stuff I want to do in here. Most of it already works on remote servers and on local machines.
# For some reason, that same role isn't working on my 14.04 chroot. So I'm going to switch this to something
# Really basic just to see what's going on
# Then we'll move all the other stuff back in, piece by piece

  # Necessary because of a bug see here: https://groups.google.com/forum/#!topic/ansible-project/P02DhiegkT8

#- name: install python-apt
  #raw: apt-get update && apt-get install python-apt -y -q

#- name: Install packages with apt
  #apt: pkg={{ item }} state=installed update_cache=true
  #with_items: pkglist

- name: Install python packages
  pip: name={{ item }}
  with_items: python_packages

#- name: Install thor with the system ruby
  #command: gem install thor
   #For some reason thor--a dependency for homesick--didn't install automatically with homesick. Weird.

#- name: Install homesick with the system ruby
  #command: gem install homesick
  #For some reason the "gem" module totally failed to install the latest version. Fortunately command works just as well here.

- name: Use homesick to clone dotfiles repo ( {{ github_username }}/{{ castle_name }} )
  command: homesick clone smcabrera/castillo-cabrera
  sudo_user: "{{ username }}"
  args:
    chdir: /home/{{ username }}
    creates: /home/{{ username }}/.homesick/repos/castillo-cabrera

- name: Remove any existing dotfiles so that homesick symlink will succeed
  file: path=/home/{{ username }}/{{ item }} state=absent
  with_items: dotfiles

#- name: Install zsh
  #shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

#- name: Remove the oh-my-zsh zshrc to replace with my own
  #file: path=/home/{{ username }}/.zshrc state=absent

- name: Use homesick to symlink dotfiles to home directory
  command: homesick symlink castillo-cabrera
  sudo_user: "{{ username }}"
  remote_user: "{{ username }}"
  args:
    chdir: /home/{{ username }}
    creates: /home/{{ username }}/.zshrc
# The above should work and, oddly, seems like it does work when I run it without sudo_user
# However when I run it as above it just takes forever and never actually finishes

- name: Get Vundle
  git: repo=https://github.com/gmarik/Vundle.vim.git dest={{ home_dir }}.vim/bundle/Vundle.vim

- name: Change shell to ZSH
  command: chsh -s /usr/bin/zsh {{ username }}

- name: Get zgen to manage zsh and plugins
  git: repo=https://github.com/tarjoilija/zgen.git dest={{ home_dir }}.zsh/zgen

#- name: Install Vim Plugins
  #command: vim +PluginInstall +qall

# For rails development
- include: rails.yml
#- include: postgresql.yml

#- name: Install gem list with the system ruby
  #gem: name={{ item }} state=latest
  #with_items: gemlist

